blank_issues_enabled: false
contact_links:
  - name: Предложить домен или сервис
    url: https://github.com/itdoginfo/allow-domains/discussions/categories/general
    about: Добавление доменов и сервисов производится через Discussions, а не Issues.
  - name: Вопрос по использованию
    url: https://t.me/itdogchat
    about: С вопросами в Telegram-чат.
